import { z } from "zod";
import { getServerConfig, createSshHandle } from "../../utils/ssh";
import type { NginxConfig } from "../../../types/server";

const schema = z.object({
  serverId: z.string(),
  config: z.object({
    workerProcesses: z.union([z.literal("auto"), z.number()]),
    workerConnections: z.number(),
    keepaliveTimeout: z.number(),
    clientMaxBodySize: z.string(),
    gzip: z.boolean(),
    gzipLevel: z.number().min(1).max(9),
    gzipTypes: z.array(z.string()),
    cacheEnabled: z.boolean(),
    cacheDuration: z.string(),
  }),
});

function generateNginxConf(
  config: NginxConfig,
  isWindows: boolean = false
): string {
  const workerProcesses =
    config.workerProcesses === "auto" ? "auto" : config.workerProcesses;

  const gzipTypesStr = config.gzipTypes.join(" ");

  if (isWindows) {
    return `# Generated by FastDeploy for Windows
worker_processes ${workerProcesses};

events {
    worker_connections ${config.workerConnections};
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  ${config.keepaliveTimeout};
    client_max_body_size ${config.clientMaxBodySize};

    ${
      config.gzip
        ? `# Gzip Settings
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level ${config.gzipLevel};
    gzip_min_length 256;
    gzip_types ${gzipTypesStr};`
        : ""
    }

    server {
        listen       80;
        server_name  localhost;

        location / {
            root   html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
`;
  }

  return `# Generated by FastDeploy
user www-data;
worker_processes ${workerProcesses};
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;

events {
    worker_connections ${config.workerConnections};
    multi_accept on;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout ${config.keepaliveTimeout};
    types_hash_max_size 2048;
    client_max_body_size ${config.clientMaxBodySize};

    ${
      config.gzip
        ? `# Gzip Settings
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level ${config.gzipLevel};
    gzip_min_length 256;
    gzip_types
        ${gzipTypesStr};`
        : ""
    }

    ${
      config.cacheEnabled
        ? `# Cache Settings
    open_file_cache max=1000 inactive=${config.cacheDuration};
    open_file_cache_valid ${config.cacheDuration};
    open_file_cache_min_uses 2;
    open_file_cache_errors on;`
        : ""
    }

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}
`;
}

export default defineEventHandler(async (event) => {
  const body = await readBody(event);
  const parsed = schema.safeParse(body);

  if (!parsed.success) {
    throw createError({
      statusCode: 400,
      message: parsed.error.issues[0]?.message || "参数验证失败",
    });
  }

  const { serverId, config } = parsed.data;
  const server = await getServerConfig(serverId);

  if (!server) {
    throw createError({ statusCode: 404, message: "服务器不存在" });
  }

  const ssh = await createSshHandle(server);
  try {
    if (server.os === "windows") {
      const confPath = `${server.workDir}\\nginx\\conf\\nginx.conf`;
      const nginxConf = generateNginxConf(config as NginxConfig, true);

      const base64Conf = Buffer.from(nginxConf, "utf8").toString("base64");
      const { code: writeCode, stderr: writeErr } = await ssh.exec(
        `powershell -Command "[System.IO.File]::WriteAllBytes('${confPath}', [System.Convert]::FromBase64String('${base64Conf}'))"`
      );

      if (writeCode !== 0) {
        throw createError({
          statusCode: 500,
          message: `写入配置失败: ${writeErr}`,
        });
      }

      const nginxDir = `${server.workDir}\\nginx`;
      const { stdout: testOut } = await ssh.exec(
        `powershell -Command "cd '${nginxDir}'; .\\nginx.exe -t 2>&1 | Out-String"`
      );

      if (
        !testOut.includes("test is successful") &&
        !testOut.includes("syntax is ok")
      ) {
        throw createError({
          statusCode: 400,
          message: `配置验证失败: ${testOut}`,
        });
      }

      return { success: true, message: "配置已更新" };
    }

    const { stdout: configPath } = await ssh.exec(
      "nginx -V 2>&1 | grep 'configure arguments' | grep -o 'conf-path=[^ ]*' | cut -d= -f2"
    );
    const confPath = configPath.trim() || "/etc/nginx/nginx.conf";

    const { stdout: backupPath } = await ssh.exec(
      `echo "${confPath}.bak.$(date +%Y%m%d%H%M%S)"`
    );
    await ssh.exec(`sudo cp ${confPath} ${backupPath.trim()}`);

    const nginxConf = generateNginxConf(config as NginxConfig);
    const { code: writeCode } = await ssh.exec(
      `echo '${nginxConf.replace(/'/g, "'\\''")}' | sudo tee ${confPath}`
    );

    if (writeCode !== 0) {
      await ssh.exec(`sudo cp ${backupPath.trim()} ${confPath}`);
      throw createError({ statusCode: 500, message: "写入配置失败" });
    }

    const { code: testCode, stderr: testErr } = await ssh.exec(
      "sudo nginx -t 2>&1"
    );
    if (testCode !== 0) {
      await ssh.exec(`sudo cp ${backupPath.trim()} ${confPath}`);
      throw createError({
        statusCode: 400,
        message: `配置验证失败: ${testErr}`,
      });
    }

    await ssh.exec(
      "sudo nginx -s reload 2>/dev/null || sudo systemctl reload nginx 2>/dev/null || sudo service nginx reload 2>/dev/null"
    );

    return { success: true, message: "配置已更新并重载" };
  } catch (err) {
    if ((err as any).statusCode) throw err;
    throw createError({
      statusCode: 500,
      message: `更新失败: ${(err as Error).message}`,
    });
  } finally {
    ssh.dispose();
  }
});
