import { z } from "zod";
import { getServerConfig, createSshHandle } from "../../utils/ssh";
import type {
  NginxInstallConfig,
  NginxInstallResult,
} from "../../../types/server";

const schema = z.object({
  serverId: z.string(),
  config: z.object({
    httpPort: z.number().default(80),
    httpsPort: z.number().default(443),
    workerProcesses: z.union([z.literal("auto"), z.number()]).default("auto"),
    gzip: z.boolean().default(true),
    gzipLevel: z.number().min(1).max(9).default(6),
    cacheEnabled: z.boolean().default(true),
    enableSsl: z.boolean().default(false),
    sslCert: z.string().optional(),
    sslKey: z.string().optional(),
  }),
});

function generateNginxConf(
  config: NginxInstallConfig,
  isWindows: boolean = false
): string {
  const workerProcesses =
    config.workerProcesses === "auto" ? "auto" : config.workerProcesses;

  if (isWindows) {
    return `# Generated by FastDeploy for Windows
worker_processes ${workerProcesses};

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    client_max_body_size 100M;

    ${
      config.gzip
        ? `# Gzip Settings
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level ${config.gzipLevel};
    gzip_min_length 256;
    gzip_types application/javascript application/json application/xml text/css text/plain text/xml;`
        : ""
    }

    server {
        listen       ${config.httpPort};
        server_name  localhost;

        location / {
            root   html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
`;
  }

  return `# Generated by FastDeploy
user www-data;
worker_processes ${workerProcesses};
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;

events {
    worker_connections 1024;
    multi_accept on;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    client_max_body_size 100M;

    ${
      config.gzip
        ? `# Gzip Settings
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level ${config.gzipLevel};
    gzip_min_length 256;
    gzip_types
        application/atom+xml
        application/javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rss+xml
        application/vnd.geo+json
        application/vnd.ms-fontobject
        application/x-font-ttf
        application/x-web-app-manifest+json
        application/xhtml+xml
        application/xml
        font/opentype
        image/bmp
        image/svg+xml
        image/x-icon
        text/cache-manifest
        text/css
        text/plain
        text/vcard
        text/vnd.rim.location.xloc
        text/vtt
        text/x-component
        text/x-cross-domain-policy
        text/xml;`
        : ""
    }

    ${
      config.cacheEnabled
        ? `# Cache Settings
    open_file_cache max=1000 inactive=20s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;`
        : ""
    }

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}
`;
}

async function installNginxWindows(
  ssh: ReturnType<typeof createSshHandle> extends Promise<infer T> ? T : never,
  config: NginxInstallConfig,
  workDir: string
): Promise<NginxInstallResult> {
  const nginxDir = `${workDir}\\nginx`;
  const nginxZip = `${workDir}\\nginx.zip`;
  const downloadUrl = "https://nginx.org/download/nginx-1.24.0.zip";

  const { code: checkCode } = await ssh.exec(
    `if exist "${nginxDir}\\nginx.exe" (echo exists) else (echo not_found)`
  );

  if (checkCode === 0) {
    const checkOutput = await ssh.exec(
      `if exist "${nginxDir}\\nginx.exe" (echo exists) else (echo not_found)`
    );
    if (checkOutput.stdout.trim() === "exists") {
      return {
        success: true,
        message: "Nginx 已安装",
        version: "1.24.0",
      };
    }
  }

  await ssh.exec(`if not exist "${workDir}" mkdir "${workDir}"`);

  const { code: dlCode, stderr: dlErr } = await ssh.exec(
    `powershell -Command "Invoke-WebRequest -Uri '${downloadUrl}' -OutFile '${nginxZip}'"`
  );

  if (dlCode !== 0) {
    return {
      success: false,
      message: "下载 Nginx 失败",
      error: dlErr,
    };
  }

  await ssh.exec(
    `powershell -Command "Expand-Archive -Path '${nginxZip}' -DestinationPath '${workDir}' -Force"`
  );
  await ssh.exec(`ren "${workDir}\\nginx-1.24.0" nginx`);
  await ssh.exec(`del "${nginxZip}"`);

  const nginxConf = generateNginxConf(config, true);
  const confPath = `${nginxDir}\\conf\\nginx.conf`;

  const base64Conf = Buffer.from(nginxConf, "utf8").toString("base64");
  const { code: writeCode, stderr: writeErr } = await ssh.exec(
    `powershell -Command "[System.IO.File]::WriteAllBytes('${confPath}', [System.Convert]::FromBase64String('${base64Conf}'))"`
  );

  if (writeCode !== 0) {
    return {
      success: false,
      message: "写入配置失败",
      error: writeErr,
    };
  }

  return {
    success: true,
    message: "Nginx 安装成功，请手动启动",
    version: "1.24.0",
  };
}

export default defineEventHandler(async (event) => {
  const body = await readBody(event);
  const parsed = schema.safeParse(body);

  if (!parsed.success) {
    throw createError({
      statusCode: 400,
      message: parsed.error.issues[0]?.message || "参数验证失败",
    });
  }

  const { serverId, config } = parsed.data;
  const server = await getServerConfig(serverId);

  if (!server) {
    throw createError({ statusCode: 404, message: "服务器不存在" });
  }

  const ssh = await createSshHandle(server);
  try {
    if (server.os === "windows") {
      return await installNginxWindows(ssh, config, server.workDir);
    }

    const { stdout: osRelease } = await ssh.exec(
      "cat /etc/os-release 2>/dev/null | head -1"
    );
    const isUbuntu = osRelease.toLowerCase().includes("ubuntu");
    const isDebian = osRelease.toLowerCase().includes("debian");
    const isCentOS =
      osRelease.toLowerCase().includes("centos") ||
      osRelease.toLowerCase().includes("rhel");

    let installCmd: string;
    if (isUbuntu || isDebian) {
      installCmd = "sudo apt-get update && sudo apt-get install -y nginx";
    } else if (isCentOS) {
      installCmd =
        "sudo yum install -y epel-release && sudo yum install -y nginx";
    } else {
      installCmd =
        "sudo apt-get update && sudo apt-get install -y nginx || sudo yum install -y nginx";
    }

    const { code: installCode, stderr: installErr } = await ssh.exec(
      installCmd
    );
    if (installCode !== 0) {
      return {
        success: false,
        message: "安装失败",
        error: installErr,
      } as NginxInstallResult;
    }

    const nginxConf = generateNginxConf(config);
    const confPath = "/etc/nginx/nginx.conf";

    const { code: writeCode } = await ssh.exec(
      `echo '${nginxConf.replace(/'/g, "'\\''")}' | sudo tee ${confPath}`
    );

    if (writeCode !== 0) {
      return {
        success: false,
        message: "写入配置失败",
      } as NginxInstallResult;
    }

    await ssh.exec("sudo mkdir -p /etc/nginx/conf.d /etc/nginx/sites-enabled");

    const { code: testCode, stderr: testErr } = await ssh.exec(
      "sudo nginx -t 2>&1"
    );
    if (testCode !== 0) {
      return {
        success: false,
        message: "配置验证失败",
        error: testErr,
      } as NginxInstallResult;
    }

    await ssh.exec(
      "sudo systemctl enable nginx 2>/dev/null || sudo chkconfig nginx on 2>/dev/null"
    );
    await ssh.exec(
      "sudo systemctl start nginx 2>/dev/null || sudo service nginx start 2>/dev/null"
    );

    const { stdout: versionOut } = await ssh.exec("nginx -v 2>&1");
    const versionMatch = versionOut.match(/nginx\/([\d.]+)/);
    const version = versionMatch ? versionMatch[1] : undefined;

    return {
      success: true,
      message: "Nginx 安装成功",
      version,
    } as NginxInstallResult;
  } catch (err) {
    return {
      success: false,
      message: "安装异常",
      error: (err as Error).message,
    } as NginxInstallResult;
  } finally {
    ssh.dispose();
  }
});
